### ISSUE TITLE
error associated with installing camoco using python 3.7.4 on mac

### ISSUE THREAD

**Issue by lisabang** [LinkageIO/Camoco#95]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**
after downgraded to 3.7.4 on mac, run into gcc error when running either "pip install camoco" or the git clone + install; don't run into error on ubuntu with 3.7.4.

* **What is the expected behavior?**

No difference between the two (unless it is memory shortfall on the part of the mac?)

* **What is the motivation / use case for changing the behavior?**

Would like to know what's going on with it and may not necessitate a change/bug fix

**Comment by schae234** [comment]
Hi Lisa!
Yeah, camoco used to be compatible with OSX, but the most recent version doesn't compile on it :( 

It is hard to address since it's external libs that dont work, so for now at least it is out of our hands. I should just add a check during installation that checks for OSX (it checks for windows, which is also unsupported) and just warn users that it isn't going to work. My hope is that soon I can do a re-write that will be more cross-platform, but that is probably a long way off!

I will also add a snippet about supported systems in the README so its transparent from the start that it was made to run on Linux.
